name: op-rollup
services:

  gateway-store:
    image: ghcr.io/zama-ai/kms-blockchain-gateway-dev:v0.8.1-rc4
    command:
      - "kv_store"
    ports:
      - "8088:8088"
    restart: on-failure

  kms-validator:
    image: ghcr.io/zama-ai/kms-blockchain-asc-dev:v0.8.1-rc4
    ports:
      - "36656:26656"
      - "36657:26657"
      - "1317:1317"
      - "9090:9090"
    entrypoint: [ "/app/bootstrap.sh" ]
    healthcheck:
      test: "wget -Sq --spider http://localhost:26657/status"
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 10s
    restart: on-failure

  connector:
    image: ghcr.io/zama-ai/kms-blockchain-connector-dev:v0.8.1-rc4
    command:
      - "kms-blockchain-connector"
    environment:
      - ASC_CONN__BLOCKCHAIN__ADDRESSES=http://kms-validator:9090
      - ASC_CONN__CORE__ADDRESSES=http://kms-core:50051
      - ASC_CONN__STORE__URL=http://gateway-store:8088
      - ASC_CONN__CORE__TIMEOUT_CONFIG__DECRYPTION__INITIAL_WAIT_TIME=1
      - ASC_CONN__CORE__TIMEOUT_CONFIG__DECRYPTION__RETRY_INTERVAL=1
      - ASC_CONN__CORE__TIMEOUT_CONFIG__REENCRYPTION__INITIAL_WAIT_TIME=1
      - ASC_CONN__CORE__TIMEOUT_CONFIG__REENCRYPTION__RETRY_INTERVAL=1
    depends_on:
      kms-validator:
        condition: service_healthy
      kms-core:
        condition: service_healthy
    restart: on-failure

  kms-core:
    image: ghcr.io/zama-ai/kms-service-dev:v0.8.1-rc4
    volumes:
      - $PWD/res/keys:/app/kms/core/service/keys:Z
    ports:
      - "50051:50051"
    healthcheck:
      test: "grpc-health-probe --addr=localhost:50051"
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 10s
    restart: on-failure

  gateway:
    image: ghcr.io/zama-ai/kms-blockchain-gateway-dev:v0.8.1-rc4
    ports:
      - "7077:7077"
    command:
      - "gateway"
    volumes:
      - ../default.toml:/app/gateway/config/default.toml:Z
    environment:
      - GATEWAY__ETHEREUM__LISTENER_TYPE=FHEVM_V1_1
      - GATEWAY__ETHEREUM__WSS_URL=ws://op-geth:8546
      - GATEWAY__ETHEREUM__HTTP_URL=http://op-geth:8545
      - GATEWAY__ETHEREUM__FHE_LIB_ADDRESS=000000000000000000000000000000000000005d
      - GATEWAY__ETHEREUM__ORACLE_PREDEPLOY_ADDRESS=c8c9303Cd7F337fab769686B593B87DC3403E0ce
      - GATEWAY__KMS__ADDRESS=http://kms-validator:9090
      - GATEWAY__KMS__KEY_ID=408d8cbaa51dece7f782fe04ba0b1c1d017b1088
      - GATEWAY__STORAGE__URL=http://gateway-store:8088
      - ASC_CONN__BLOCKCHAIN__ADDRESSES=http://kms-validator:9090
      - GATEWAY__ETHEREUM__RELAYER_KEY=7ec931411ad75a7c201469a385d6f18a325d4923f9f213bd882bbea87e160b67
      - RUST_BACKTRACE=1
      - GATEWAY__ETHEREUM__CHAIN_ID=38070
    extra_hosts:
      - "fhevm-bor:host-gateway"
    depends_on:
      op-geth:
        condition: service_healthy
      kms-validator:
        condition: service_healthy
    restart: on-failure

  op-batcher:
    depends_on:
      op-geth:
        condition: service_started
        required: false
      op-node:
        condition: service_started
        required: false
    entrypoint:
      - op-batcher
    environment:
      OP_BATCHER_L1_ETH_RPC: https://puppynet.shibrpc.com
      OP_BATCHER_L2_ETH_RPC: http://op-geth:8545
      OP_BATCHER_MAX_CHANNEL_DURATION: "1"
      OP_BATCHER_NUM_CONFIRMATIONS: "1"
      OP_BATCHER_POLL_INTERVAL: 1s
      OP_BATCHER_PRIVATE_KEY: 9c61beaade5739c0c60e0a10b4b720ded343978d8c7788c846908585d7128594
      OP_BATCHER_RESUBMISSION_TIMEOUT: 30s
      OP_BATCHER_ROLLUP_RPC: http://op-node:8547
      OP_BATCHER_RPC_ADDR: 0.0.0.0
      OP_BATCHER_RPC_ENABLE_ADMIN: "true"
      OP_BATCHER_RPC_PORT: "8548"
      OP_BATCHER_SAFE_ABORT_NONCE_TOO_LOW_COUNT: "3"
      OP_BATCHER_SUB_SAFETY_MARGIN: "6"
    env_file:
      - .env
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-batcher:v1.9.0
    networks:
      op-network: {}
    ports:
      - target: 8548
        published: "8548"
        protocol: tcp
    restart: unless-stopped
    stop_grace_period: 5m0s

  op-geth:
    entrypoint:
      - /bin/sh
      - -c
      - mkdir -p /logs && geth init --datadir=datadir genesis.json && geth
    environment:
      GETH_AUTHRPC_ADDR: 0.0.0.0
      GETH_AUTHRPC_JWTSECRET: /root/jwt.txt
      GETH_AUTHRPC_PORT: "8551"
      GETH_AUTHRPC_VHOSTS: '*'
      GETH_DATADIR: /datadir
      GETH_GCMODE: archive
      GETH_HTTP: "true"
      GETH_HTTP_ADDR: 0.0.0.0
      GETH_HTTP_API: web3,debug,eth,txpool,net,engine
      GETH_HTTP_CORSDOMAIN: '*'
      GETH_HTTP_PORT: "8545"
      GETH_HTTP_VHOSTS: '*'
      GETH_MAXPEERS: "0"
      GETH_NETWORKID: "38070"
      GETH_NODISCOVER: "true"
      GETH_ROLLUP_DISABLETXPOOLGOSSIP: "true"
      GETH_SYNCMODE: full
      GETH_WS: "true"
      GETH_WS_ADDR: 0.0.0.0
      GETH_WS_API: debug,eth,txpool,net,engine
      GETH_WS_ORIGINS: '*'
      GETH_WS_PORT: "8546"
      TFHE_EXECUTOR_CONTRACT_ADDRESS: 0x05fD9B5EFE0a996095f42Ed7e77c390810CF660c
      FHEVM_GO_KEYS_DIR: ./op-geth/keys
    env_file:
      - .env
    image: shibainuofficial/fhe-op-geth:v1.0.0
    networks:
      op-network: {}
    ports:
      - target: 8545
        published: "8545"
        protocol: tcp
      - target: 8546
        published: "8546"
        protocol: tcp
      - target: 8551
        published: "8551"
        protocol: tcp
    restart: unless-stopped
    stop_grace_period: 5m0s
    volumes:
      - type: bind
        source: ./op-geth
        target: /datadir
      - type: bind
        source: ./jwt.txt
        target: /root/jwt.txt
      - type: bind
        source: ./genesis.json
        target: /genesis.json
      - $PWD/network-fhe-keys:/network-fhe-keys:Z  # New volume for FHE keys
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: "curl -s -H \"Connection: Upgrade\" -H \"Upgrade: websocket\" http://localhost:8546"
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 20s

  op-node:
    entrypoint:
      - op-node
    environment:
      OP_NODE_L1_BEACON_IGNORE: "true"
      OP_NODE_L1_ETH_RPC: https://puppynet.shibrpc.com
      OP_NODE_L1_HTTP_POLL_INTERVAL: 5s
      OP_NODE_L1_RPC_KIND: basic
      OP_NODE_L1_TRUST_RPC: "false"
      OP_NODE_L2_ENGINE_AUTH: /app/jwt.txt
      OP_NODE_L2_ENGINE_RPC: http://op-geth:8551
      OP_NODE_P2P_DISABLE: "true"
      OP_NODE_ROLLUP_CONFIG: /app/rollup.json
      OP_NODE_RPC_ADDR: 0.0.0.0
      OP_NODE_RPC_ENABLE_ADMIN: "true"
      OP_NODE_RPC_PORT: "8547"
      OP_NODE_SEQUENCER_ENABLED: "true"
      OP_NODE_SEQUENCER_L1_CONFS: "5"
      OP_NODE_VERIFIER_L1_CONFS: "4"
    env_file:
      - .env
    image: shibainuofficial/devrollup-op-node:v1.0.8
    networks:
      op-network: {}
    ports:
      - target: 8547
        published: "8547"
        protocol: tcp
    restart: unless-stopped
    stop_grace_period: 5m0s
    volumes:
      - type: bind
        source: ./jwt.txt
        target: /app/jwt.txt
      - type: bind
        source: ./rollup.json
        target: /app/rollup.json
        
  op-proposer:
    depends_on:
      op-geth:
        condition: service_started
        required: false
      op-node:
        condition: service_started
        required: false
    entrypoint:
      - op-proposer
    environment:
      OP_PROPOSER_L1_ETH_RPC: https://puppynet.shibrpc.com
      OP_PROPOSER_L2OO_ADDRESS: 0x578B9eDF97053cfF820403F3a0e271d9855BcB3D
      OP_PROPOSER_POLL_INTERVAL: 12s
      OP_PROPOSER_PRIVATE_KEY: 28cf40c8e4b2200424f3c0a85cafbef16fd01d7d772ebe40d087db170e364f0b
      OP_PROPOSER_ROLLUP_RPC: http://op-node:8547
      OP_PROPOSER_RPC_PORT: "8560"
    env_file:
      - .env
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-proposer:v1.9.0
    networks:
      op-network: {}
    ports:
      - target: 8560
        published: "8560"
        protocol: tcp
    restart: unless-stopped
    stop_grace_period: 5m0s
networks:
  op-network:
    name: op-network
    driver: bridge
